### ISSUE TITLE
🚀 [feature] 카메라 인식 페이지 구현

### ISSUE THREAD

**Issue by bongsh0112** [Gosrock/Ticket-Admin-22th#2]
# 🤖 기능 개요

Web Cam으로 티켓 QR Code를 인식하고 서버에 티켓 uuid를 보내 응답을 받아 입장 성공 여부를 판단합니다.

### ✅ Implement TODO

- [x] git branch 새로 만들기
- [x] QR Code Reader 구현하기
- [x] 서버 통신 테스트하기

**Comment by ImNM** [comment]
good 잘작성하셨어요!
@bongsh0112 
깃허브 앱도있거둔? 이렇게 어싸인하면 알림와

**Comment by ImNM** [comment]
그 프로필에 알림설정 가서 모든알림 다키삼
